# Generated by Django 4.2.2 on 2023-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('I', 'En etapa de inscripcioó'), ('P', 'En progreso'), ('F', 'Finalizado')], default='I', max_length=1, verbose_name='Estado'),
        ),
    ]
