# Generated by Django 4.2.2 on 2023-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
    ]
